from csvReader import *
import matplotlib.pyplot as plt
"""
Plot CSV files in the format generated by the PPP unstuffing plotter/logger, if the csv
and print to console options are used. 
"""

data = read_csv("log.csv",'\n')
fdata,names = format_csv(data)


time = fdata[len(fdata)-1]  #copy out time vector, which all other lines are referenced to
fdata = fdata[0:len(fdata)-1]   #remove last element which is always time in milliseconds


fig,ax = plt.subplots()
for i,arr in enumerate(fdata):
    ax.plot(time, arr)
ax.legend(names)
plt.show()